package com.examenfinalv2.modificacioncostofee;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AprobarFee implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Motivo de Modificacion")
	private java.lang.String motivoModificacion;
	@org.kie.api.definition.type.Label("Fecha Estimada de Inicio")
	private java.util.Date fechaEstimadaInicio;
	@org.kie.api.definition.type.Label("Aprobado?")
	private java.lang.Boolean aprueba;
	@org.kie.api.definition.type.Label("Comentario de Aprobacion")
	private java.lang.String comentarioAprobacion;
	@org.kie.api.definition.type.Label("Solicitante")
	private java.lang.String solicitante;
	@org.kie.api.definition.type.Label("Fecha de Solicitud")
	private java.util.Date fechaSolicitud;

	@org.kie.api.definition.type.Label("Lineas de Produccion")
	private java.util.List<com.examenfinalv2.modificacioncostofee.Feelineas> feeLineas;

	@org.kie.api.definition.type.Label(value = "Comentario")
	private java.lang.String comentario;

	public AprobarFee() {
	}

	public java.lang.String getMotivoModificacion() {
		return this.motivoModificacion;
	}

	public void setMotivoModificacion(java.lang.String motivoModificacion) {
		this.motivoModificacion = motivoModificacion;
	}

	public java.util.Date getFechaEstimadaInicio() {
		return this.fechaEstimadaInicio;
	}

	public void setFechaEstimadaInicio(java.util.Date fechaEstimadaInicio) {
		this.fechaEstimadaInicio = fechaEstimadaInicio;
	}

	public java.lang.Boolean getAprueba() {
		return this.aprueba;
	}

	public void setAprueba(java.lang.Boolean aprueba) {
		this.aprueba = aprueba;
	}

	public java.lang.String getComentarioAprobacion() {
		return this.comentarioAprobacion;
	}

	public void setComentarioAprobacion(java.lang.String comentarioAprobacion) {
		this.comentarioAprobacion = comentarioAprobacion;
	}

	public java.lang.String getSolicitante() {
		return this.solicitante;
	}

	public void setSolicitante(java.lang.String solicitante) {
		this.solicitante = solicitante;
	}

	public java.util.Date getFechaSolicitud() {
		return this.fechaSolicitud;
	}

	public void setFechaSolicitud(java.util.Date fechaSolicitud) {
		this.fechaSolicitud = fechaSolicitud;
	}

	public java.util.List<com.examenfinalv2.modificacioncostofee.Feelineas> getFeeLineas() {
		return this.feeLineas;
	}

	public void setFeeLineas(
			java.util.List<com.examenfinalv2.modificacioncostofee.Feelineas> feeLineas) {
		this.feeLineas = feeLineas;
	}

	public java.lang.String getComentario() {
		return this.comentario;
	}

	public void setComentario(java.lang.String comentario) {
		this.comentario = comentario;
	}

	public AprobarFee(
			java.lang.String motivoModificacion,
			java.util.Date fechaEstimadaInicio,
			java.lang.Boolean aprueba,
			java.lang.String comentarioAprobacion,
			java.lang.String solicitante,
			java.util.Date fechaSolicitud,
			java.util.List<com.examenfinalv2.modificacioncostofee.Feelineas> feeLineas,
			java.lang.String comentario) {
		this.motivoModificacion = motivoModificacion;
		this.fechaEstimadaInicio = fechaEstimadaInicio;
		this.aprueba = aprueba;
		this.comentarioAprobacion = comentarioAprobacion;
		this.solicitante = solicitante;
		this.fechaSolicitud = fechaSolicitud;
		this.feeLineas = feeLineas;
		this.comentario = comentario;
	}

}