package com.examenfinalv2.modificacioncostofee;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Feelineas implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Linea de Produccion")
	private java.lang.String linea;
	@org.kie.api.definition.type.Label(value = "Fee Estimado")
	private java.lang.Integer fee;
	@org.kie.api.definition.type.Label(value = "Observaciones")
	private java.lang.String observaciones;

	public Feelineas() {
	}

	public java.lang.String getLinea() {
		return this.linea;
	}

	public void setLinea(java.lang.String linea) {
		this.linea = linea;
	}

	public java.lang.Integer getFee() {
		return this.fee;
	}

	public void setFee(java.lang.Integer fee) {
		this.fee = fee;
	}

	public java.lang.String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(java.lang.String observaciones) {
		this.observaciones = observaciones;
	}

	public Feelineas(java.lang.String linea, java.lang.Integer fee,
			java.lang.String observaciones) {
		this.linea = linea;
		this.fee = fee;
		this.observaciones = observaciones;
	}

}